services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  gateway:
    build: 
      context: .
      dockerfile: gateway.Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis

  queue_manager:
    build:
      context: .
      dockerfile: queue_manager.Dockerfile
    container_name: queue_manager
    ports:
      - "8001:8001"
    depends_on:
      - redis

  worker1:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker1
    environment:
      - WORKER_ID=worker1
    depends_on:
      - redis
      - queue_manager


  worker2:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker2
    environment:
      - WORKER_ID=worker2
    depends_on:
      - redis
      - queue_manager

  monitoring:
    build: 
      context: .
      dockerfile: monitoring.Dockerfile
    container_name: monitoring
    ports:
      - "8002:8002"
    depends_on:
      - redis
